export const SET_MESSAGES = 'SET_MESSAGES';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_USER_NAME_SENT = 'SET_USER_NAME_SENT';

export const FETCH_FRIENDS_LIST_START = 'FETCH_FRIENDS_LIST_START'
export const FETCH_FRIENDS_LIST_SUCCESS = 'FETCH_FRIENDS_LIST_SUCCESS';
export const FETCH_FRIENDS_LIST_FAIL = 'FETCH_FRIENDS_LIST_FAIL'
export const FETCH_FRIENDS_DATA_START = 'FETCH_FRIENDS_DATA_START';
export const FETCH_FRIENDS_DATA_SUCCESS = 'FETCH_FRIENDS_DATA_SUCCESS';
export const FETCH_FRIENDS_DATA_FAIL = 'FETCH_FRIENDS_DATA_FAIL';
export const FETCHED_FRIENDS = 'FETCHED_FRIENDS';
export const SET_CURR_FRIEND = 'SET_CURR_FRIEND';
export const ADD_FRIEND_MESSAGE = 'ADD_FRIEND_MESSAGE';
export const ADD_NEW_FRIEND = 'ADD_NEW_FRIEND';
export const READ_MESSAGE = 'READ_MESSAGE';
export const USER_STATUS_UPDATE = 'USER_STATUS_UPDATE'; 

export const SET_IS_MOBILE = 'SET_IS_MOBILE';
